<?php
namespace B2B\BlogBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * PostAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getLatestCompany($offset,$limit)
 {
    $qb = $this->createQueryBuilder('b')
               ->select('b')
               ->setFirstResult( $offset )
               ->setMaxResults( $limit );

    return $qb->getQuery()
              ->getResult();
  } 
}
